### ISSUE TITLE
Update Natural Language docs and guides

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1045]
Update docs using new content from https://cloud.google.com/natural-language/docs/, as soon as it is available.

- [x] Update language limitations to full support for English, Spanish, and Japanese
- [x] Update all Syntax examples to use new `syntax` method. (#1037)
- [x] Resolve all docs `TODO`s (Most or all will be found in `PartOfSpeech`. (#1038)
- [x] Improve descriptions of `EntityMention.type` values. (#1039)
- [x] Improve description of `mid` attribute. (#1040)
- [x] Improve description of `score` attribute. (#1041, #1042 )
- [x] Update all headline Sentiment examples to show the new sentiment methods on `Sentence`. (#1043)
- [x] Add example, description, and possible values for `encoding_type` param. (#1044)
